### ISSUE TITLE
Impossible to generate a DSA or ElGamal key with a randomly generated DL group

### ISSUE THREAD

**Issue by teythoon** [randombit/botan-rs#110]
AFAICS there is no parameter string to pass to `Privkey::create` that selects a randomly generated DL group.

**Comment by randombit** [comment]
Can you take a look at #110?

**Comment by teythoon** [comment]
#111 seems to work fine.

**Comment by randombit** [comment]
Just released `botan 0.10.6` with this included

Though I realized after I published, this probably should be `0.11.0` instead? The versioning is a bit wonky ... it may be time to commit to 1.0 on this crate.

**Comment by teythoon** [comment]
Thanks for the prompt fix!

WRT the 1.0 release I'd still love to see #81 addressed first.  I think this would make the interface more ergonomic and more robust.

More ergonomic because while working on this I again read through the Botan source in order to figure out whether there is a magic parameter string that would do what I want.

More robust because it doesn't leak an botan-ffi implementation detail into the Rust API.  And, I actually first passed `bits.to_string()` as parameter, thinking that that should work, and my tests didn't catch that mistake, because failing to generate the key because of the wrong parameter looked to the test like the algorithm wasn't implemented by the underlying cryptographic library.
