### ISSUE TITLE
Expose PBKDF timed

### ISSUE THREAD

**Issue by dewyatt** [randombit/botan-rs#13]
I don't see a way of doing timed PBKDF directly or calculating an iteration count/tuning.

**Comment by randombit** [comment]
You're right. `botan_pwdhash_timed` needs to be exposed. It is declared in `botan-sys` just no high level wrapper.

**Comment by dewyatt** [comment]
Hey thanks a bunch @randombit! I was probably going to do a PR in the future, but you've saved me the trouble! :)
