### ISSUE TITLE
Single threaded botan-src build

### ISSUE THREAD

**Issue by est31** [randombit/botan-rs#22]
If I enable the vendored feature, the build takes a long time because it's single threaded.

I'm not sure how to enable parallel make. `make -j $NUM_JOBS` [is not the solution](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts) but I'm not sure how one can do jobserver passthrough.

**Comment by est31** [comment]
cc #15 @breard-r

**Comment by randombit** [comment]
Yeah it would be nice to fix this. Maybe the short term approach is just `-j $NUM_JOBS` even if not optimal.

**Comment by est31** [comment]
Yeah so the issue is that cargo currently doesn't set `MAKEFLAGS` but only `CARGO_MAKEFLAGS` which make obviously has no idea what to do with. Thus to make it seems that there is no jobserver running at all, with the expectable consequences. https://github.com/alexcrichton/jobserver-rs/issues/24#issuecomment-700083933

**Comment by est31** [comment]
Btw for reference this is how the cmake crate does it as well, it just copies over the env var: https://docs.rs/cmake/0.1.44/src/cmake/lib.rs.html#718
