### ISSUE TITLE
Linking failure when using vendored feature

### ISSUE THREAD

**Issue by est31** [randombit/botan-rs#23]
There seems to be a linking failure on travis when I test the new botan feature to vendor sources.

Link to a failed build: https://travis-ci.com/github/est31/rcgen/jobs/391529962

Excerpt from the logs:

```
error: linking with `cc` failed: exit code: 1
[...]
note: /usr/bin/ld: /home/travis/build/est31/rcgen/target/debug/deps/libbotan_sys-59cd180e5db8bbbc.rlib(ffi.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC

          /home/travis/build/est31/rcgen/target/debug/deps/libbotan_sys-59cd180e5db8bbbc.rlib: error adding symbols: Bad value

          collect2: error: ld returned 1 exit status
```

It works locally on my machine.

**Comment by randombit** [comment]
Interesting. Botan always compiles with PIC even for a static library only target, to support linking the library into an .so or a PIE executable. So I'm not sure how this could happen.

**Comment by est31** [comment]
Using newer ubuntu versions (18.04 instead of 16.04) fixed the issue for me: https://github.com/est31/rcgen/commit/edf1095fa460f93ac8fdc11e703fcfd2bad5c413
