### ISSUE TITLE
New crates.io release

### ISSUE THREAD

**Issue by est31** [randombit/botan-rs#27]
Hi, I wondered whether it would be possible to make a new release of the botan-sys crate on crates.io that has #24 included so that compile time for botan is reduced. Thanks!

**Comment by randombit** [comment]
I think you mean the `botan-src` crate? And, sure. Actually we are overdue anyway for a new release as it still uses 2.16.0 and upstream is at 2.17.1 now

**Comment by randombit** [comment]
botan-src 0.21701.0 published to crates.io now

**Comment by randombit** [comment]
(There are also new `botan-sys` and `botan` crates to match)
