### ISSUE TITLE
better way to use botan-rs on Windows?

### ISSUE THREAD

**Issue by FischLu** [randombit/botan-rs#58]
Hello,

My botan on Windows is install via vcpkg, the lib name is botan.lib, however when I use botan-rs in my project, the system error shows `LINK : fatal error LNK1181: cannot open input file 'botan-2.lib'` (I have provided the lib path via `-L`), the only way to bypass it I know is to copy botan.lib to a new file with name botan-2.lib, is there any elegant solutions? Thanks!

**Comment by randombit** [comment]
I had forgotten that the Windows library doesn't include the version.

I think we can modify `botan-sys/build.rs` so this handles the situation correctly for Windows as well.

For Botan 3 I have opened a PR to include the version there as well, so the problem would go away in that case.

**Comment by randombit** [comment]
Can you try the patch in #59?

**Comment by FischLu** [comment]
> Can you try the patch in #59?

Just tried the patch, works fine, thanks!

**Comment by randombit** [comment]
Thanks for reporting this, and for testing! I just published 0.9.1 to crates.io which includes the fix.
