### ISSUE TITLE
Feature no-std should be std instead

### ISSUE THREAD

**Issue by randombit** [randombit/botan-rs#92]
As features should be additive.

**Comment by thewalker77** [comment]
@randombit are you working on that, I was just hit with the exact same realization. if you are not, I will be working on it.

**Comment by randombit** [comment]
@thewalker77 Not working on this right now, happy to review a patch

**Comment by randombit** [comment]
#104

**Comment by randombit** [comment]
Fixed now on master, will be available in 0.11.0 released probably next week
